services:
  - type: web
    name: fra-atlas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd frapro && gunicorn --bind 0.0.0.0:$PORT frapro.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false