# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('geometry', models.TextField(blank=True, help_text='State boundary JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('geometry', models.TextField(blank=True, help_text='District boundary JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='main.state')),
            ],
            options={
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='ClaimStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims_filed', models.PositiveIntegerField(default=0)),
                ('claims_approved', models.PositiveIntegerField(default=0)),
                ('claims_rejected', models.PositiveIntegerField(default=0)),
                ('claims_under_review', models.PositiveIntegerField(default=0)),
                ('claims_pending', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_stats', to='main.district')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('MGNREGA', 'Mahatma Gandhi National Rural Employment Guarantee Act'), ('JAL_JEEVAN', 'Jal Jeevan Mission'), ('PMAY_G', 'Pradhan Mantri Awas Yojana - Gramin'), ('DDU_GKY', 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana'), ('PM_KISAN', 'PM Kisan Samman Nidhi'), ('SWACHH_BHARAT', 'Swachh Bharat Mission')], max_length=20)),
                ('reason', models.TextField()),
                ('priority_score', models.IntegerField(default=1, help_text='1-5 priority score')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_recommendations', to='main.district')),
            ],
            options={
                'unique_together': {('district', 'scheme')},
            },
        ),
    ]