# Generated by Django 5.2.5 on 2025-09-04 05:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.AddField(
            model_name='asset',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Spatial boundary of the asset', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='asset',
            name='identified_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('water_bodies', 'Water Bodies'), ('forest_cover', 'Forest Cover'), ('agricultural_land', 'Agricultural Land'), ('homesteads', 'Homesteads')], max_length=20),
        ),
        migrations.CreateModel(
            name='ClaimStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims_filed', models.PositiveIntegerField(default=0)),
                ('claims_approved', models.PositiveIntegerField(default=0)),
                ('claims_rejected', models.PositiveIntegerField(default=0)),
                ('claims_under_review', models.PositiveIntegerField(default=0)),
                ('claims_pending', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_stats', to='main.district')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='main.district'),
        ),
        migrations.CreateModel(
            name='FRAClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('area_claimed', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fra_claims', to='main.district')),
            ],
        ),
        migrations.CreateModel(
            name='PattaHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('patta_number', models.CharField(max_length=50, unique=True)),
                ('land_area', models.DecimalField(decimal_places=2, help_text='Land area in acres', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patta_holders', to='main.district')),
                ('fra_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patta_holders', to='main.fraclaim')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='main.state'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
    ]
