# Generated by Django 5.2.5 on 2025-09-04 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_district_state_remove_asset_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='district',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='District boundary', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='district',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fraclaim',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Claimed land boundary', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='fraclaim',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pattaholder',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Patta holder location', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pattaholder',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='state',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='State boundary', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='state',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
