# Generated by Django 5.2.5 on 2025-09-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_asset_location_district_geometry_district_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('MGNREGA', 'Mahatma Gandhi National Rural Employment Guarantee Act'), ('JAL_JEEVAN', 'Jal Jeevan Mission'), ('PMAY_G', 'Pradhan Mantri Awas Yojana - Gramin'), ('DDU_GKY', 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana'), ('PM_KISAN', 'PM Kisan Samman Nidhi'), ('SWACHH_BHARAT', 'Swachh Bharat Mission')], max_length=20)),
                ('reason', models.TextField()),
                ('priority_score', models.IntegerField(default=1, help_text='1-5 priority score')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_recommendations', to='main.district')),
            ],
            options={
                'unique_together': {('district', 'scheme')},
            },
        ),
    ]
